apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
    creationTimestamp: 2017-07-04T07:03:14Z
    generation: 1
    labels:
      io.kompose.service: archivist
    name: archivist
    namespace: default
    resourceVersion: "2315678"
    selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/archivist
    uid: d9610be5-6086-11e7-8167-42010a800254    
  spec:
    replicas: 1
    selector:
      matchLabels:
        io.kompose.service: archivist
    strategy:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: archivist
      spec:
        containers:
        - image: us.gcr.io/multichain-prod/archivist:v1
          imagePullPolicy: Always
          name: archivist
          ports:
          - containerPort: 3001
            protocol: TCP
          resources: {}
          stdin: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          tty: true
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: 2017-07-04T07:03:14Z
      lastUpdateTime: 2017-07-04T07:03:14Z
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    observedGeneration: 1
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
kind: List
metadata: {}
resourceVersion: ""
selfLink: ""