apiVersion: v1
items:
- kind: PersistentVolume
  apiVersion: v1
  metadata:
    name: archivist-volume
    labels:
      type: local
  spec:
    storageClassName: manual 
    capacity:
      storage: 10Gi
    accessModes:
      - ReadWriteMany
    hostPath:
      path: "/src/storage"
- kind: PersistentVolumeClaim
  apiVersion: v1
  metadata:
    name: archivist-claim
  spec:
    storageClassName: manual
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: 3Gi
kind: List
metadata: {}
resourceVersion: ""
selfLink: ""